[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "libsodium",
  "gcc"
]

[phases.install]
cmds = [
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r misc/requirements.txt"
]

[start]
cmd = "python3 -m bot.main"