[phases.setup]
nixPkgs = [
  "python3Full",
  "libsodium",
  "gcc"
]

[phases.install]
cmds = [
  "pip3 install --break-system-packages -r misc/requirements.txt"
]

[start]
cmd = "python3 -m bot.main"